### ISSUE TITLE
Device Plugin is not returning with an error, Pod not restarted

### ISSUE THREAD

**Issue by zvonkok** [NVIDIA/k8s-device-plugin#170] opened 2020-05-14 17:21 UTC
---

### 1. Issue or feature description
The device plugin is not returning an error if it fails. 
```
020/05/14 02:11:19 Loading NVML
2020/05/14 02:11:19 Failed to initialize NVML: could not load NVML library.
2020/05/14 02:11:19 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2020/05/14 02:11:19 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/05/14 02:11:19 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start
```
The Pod shows Running and is not restarted. During scale-up the DevicePlugin can start before the driver and hook are deployed. 

### 2. Steps to reproduce the issue

Deploy the GPU operator on a single node and scale up to two nodes (OpenShift).

**Comment by klueska** [comment] 2020-05-15 11:53
Hi @zvonkok,

I agree that this is strange and unexpected for nodes that have GPUs on them. However, the plugin was designed so that it could land on non-GPU nodes (e.g. in a mixed cluster) and avoid sitting in a constant restart loop.

That said, it sits on an empty `select {}` loop when it reaches this condition, so you can always send it a `SIGTERM` via `docker exec` to force it to restart once you know the driver is installed, something like:
```
docker exec <plugin-pod> kill SIGTERM
```

I'm open to suggestions on how to deal with this differently, but there is no obvious solution to me.

**Comment by zvonkok** [comment] 2020-05-15 15:28
@klueska I remember some discussion about this very topic, I am just curious why would someone want to run the DP on non GPU nodes? 

What about adding a script that does a restart internally in the Pod rather than having k8s  scheduler doing that? 

On error the DP could send a signal that the script is trapping on, but it can go still into `select {}`, with this signal and the restartCount you can restart the DP with a timeout, on a GPU  node hopefully the restart and timeout would be enough to get it into a healthy state on a non-GPU node it would just sit there after it reaches the restartCount.

**Comment by zvonkok** [comment] 2020-05-15 15:29
@klueska Is it just the fact that they do not have any nodeSelector or Taints on their DaemonSet when running in the heterogeneous cluster?

**Comment by klueska** [comment] 2020-05-15 15:30
Yes, I was just about to answer with that.

**Comment by klueska** [comment] 2020-05-15 15:36
Arguably, everyone should be using a node selector. In fact, they should be deploying the gpu-feature-daemonset in their cluster and using the labels it presents as the labels in the `nodeSelector`.  In practice, not everyone does this though, unfortunately.

Even with this, there is still the chicken / egg problem you are running into since `gpu-feature-discovery` will not report GPU labels until the driver is installed. You would need some out-of-band mechanism to label your nodes as GPU nodes (using your own custom schema) and then rely on that for deploying the k8s-plugin.

**Comment by klueska** [comment] 2020-05-15 15:41
> What about adding a script that does a restart internally in the Pod rather than having k8s scheduler doing that?

We already run a restart loop internally for connection errors with the kubelet (which typically result from the a kubelet upgrade or the kubelet being duty cycled to swap some command line flags).

In theory, we could add NVML detection failures to this loop as well, but then you would end up looping forever on non-GPU nodes that (arguably out of bad cluster design) had the daemonset land on them because they weren't using an out of band mechanism to label/taint the nodes for the `nodeSelector`.

**Comment by zvonkok** [comment] 2020-05-15 15:43
@klueska That is the bootstrap problem we are solving with NFD. NFD will label the GPU nodes with the PCI Vendor ID (10de). Either do it manually or do it with NFD. 

Indeed, if we have special resources in the cluster either label them or taint them. 
Having a Pod running even if it is error'ing out is "bad" practice. This kinda bypasses the k8s patterns on how to or how the cluster can react on errors.

**Comment by zvonkok** [comment] 2020-05-15 15:46
This should be a clean solution, we are trying here to circumvent or solve bad practices when dealing with GPU nodes. 

DaemonSet(s) are not made for running to completion and we are trying here to implement such a solution.

**Comment by klueska** [comment] 2020-05-15 16:15
I think I can agree with that. This part of the code / this design decision predates my involvement with it, so I was mostly trying to justify why it exists the way it does.

The one downside is that you can't just take 

Going forward, I agree that we should error out here, with a more descriptive error message listing the different reasons it might have occurred:

1) You incorrectly deployed the daemonset on a node that was never intended to have GPUs on it -- use a node selector to correct this.
2) The GPU driver is not installed (or is incorrectly installed) on this node -- you need to debug why this might have happened.

The one downside is obviously that you will no longer be able to simply create the daemonset directly from the `plugin.yml` hosted on github unless all of the nodes in your cluster have GPUs on them, i.e.
```
$ kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta6/nvidia-device-plugin.yml
```
Of course you still "can", but the nodes without GPUs will have a failing daemonset on them unnecessarily.

**Comment by zvonkok** [comment] 2020-05-19 00:47
That would be great if we can have more meaningfull error messages, there are more checks and error messages that I  have seen in the past: 

1. NVIDIA drivers loaded but the prestart hook did not get executed
2. NVIDIA drivers loaded prestart hook fired but cannot access the devices (permission denied) 

Yes, you can still execute but with more verbose error messages users could be "warned" that they are doing something not supported.

**Comment by zvonkok** [comment] 2020-07-02 18:01
@klueska Any update on this? Thanks!

**Comment by klueska** [comment] 2020-07-06 11:57
@zvonkok Not yet. I will make sure and include this as part of the next release (at the end of July)

**Comment by klueska** [comment] 2020-07-20 12:19
Update out for review (only top 2 commits):
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/40

Includes commits from dependent MR:
https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/41

**Comment by klueska** [comment] 2020-07-20 12:28
One question I have is whether we should sleep / retry some number of times before errorring out.

As you mentioned, during scale-up the DevicePlugin can start before the driver and hook are deployed. Sleeping / retrying some number of times would reduce the likelihood that K8s would need to redeploy it if the driver comes online quickly enough.

**Comment by klueska** [comment] 2020-07-20 20:33
PRs merged.

**Closed by klueska** 2020-07-20 20:33 UTC
